services:
  mongo:
    image: rchard237/mongo:8.0
    container_name: mongo
    restart: always
    command: ["mongod","--auth","--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: rchard237/redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: rchard237/roomster-app
    container_name: roomster-app
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://appuser:privet345@mongo:27017/chatdb?authSource=chatdb"
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - "SPRING_DATA_REDIS_URL=redis://redis:6379"

volumes:
  mongo_data:
  redis_data: